# Generated by Django 3.0.6 on 2020-09-20 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itjobs',
            name='user',
        ),
    ]
