# Generated by Django 3.0.6 on 2020-09-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
        ('adminapp', '0002_remove_itjobs_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='itjobs',
            name='user',
            field=models.ManyToManyField(to='userapp.User'),
        ),
    ]
