# Generated by Django 3.0.6 on 2020-09-23 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_auto_20200923_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itjobs',
            old_name='admin',
            new_name='table',
        ),
    ]
