# Generated by Django 3.0.6 on 2020-09-27 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_users_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminapp', '0009_auto_20200923_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='MechJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('desgination', models.CharField(max_length=100)),
                ('experience', models.FloatField()),
                ('package', models.FloatField()),
                ('vaccancy', models.IntegerField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.Address')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ManyToManyField(to='userapp.Users')),
            ],
        ),
        migrations.CreateModel(
            name='CivilJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('desgination', models.CharField(max_length=100)),
                ('experience', models.FloatField()),
                ('package', models.FloatField()),
                ('vaccancy', models.IntegerField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.Address')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ManyToManyField(to='userapp.Users')),
            ],
        ),
    ]
