# Generated by Django 3.0.6 on 2020-10-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_civiljobs_mechjobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itjobs',
            old_name='table',
            new_name='hrtable',
        ),
    ]
