# Generated by Django 3.0.6 on 2020-10-07 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_auto_20201007_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='civiljobs',
            old_name='table',
            new_name='hrtable',
        ),
        migrations.RenameField(
            model_name='mechjobs',
            old_name='table',
            new_name='hrtable',
        ),
    ]
