# Generated by Django 3.0.6 on 2020-09-21 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_auto_20200921_0930'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
